셀렉트 컴포넌트 제작 및 프로필 페이지 기능 구현
Sassy-Project/front-setup pull request #61
Opened 2023-04-14 07:38 UTC by Eriniss

## 개요 :mag:

셀렉트 컴포넌트의 스타일링과 어트리뷰트를 설정하였습니다.
라벨 컴포넌트와 셀렉트 컴포넌트를 합쳐 하나의 통합 셀렉트 컴포넌트를 생성하였습니다.
프로필 페이지의 기능을 대부분 구현하였습니다.

## 작업사항 :memo:
![스크린샷 2023-04-14 16 35 31](https://user-images.githubusercontent.com/103402910/231976684-46c8eeab-1427-46c6-930f-3b72b294587d.png)

리뷰
https://velog.io/@jqk2195/2023.04.14%EA%B8%88-%EC%BD%94%EB%93%9C%EB%A6%AC%EB%B7%B0

2023-04-14 08:04 UTC, Eriniss commented
리뷰 URL에 들어가시면 자세한 사항들이 적혀있습니다

2023-04-14 08:07 UTC, 1yoouoo requested changes

2023-04-14 08:07 UTC, 1yoouoo commented on src/components/styled-components/BasicInput.tsx
> +  Omit<InputProps, 'name' | 'id' | 'type' | 'value' | 'onChange' | 'onBlur' | 'placeholder'>
타입 유틸리티 중에 Omit을 사용하셨는데 

8개중에 7개 를 제외하는 코드보다는
8개중 1개를 선택하는 Pick을 사용하시는건 어떨까요?

2023-04-14 08:07 UTC, 1yoouoo commented on src/components/LabelBasicInput/index.tsx
> +const LabelBasicInput = (props: any) => {
```suggestion
const LabelBasicInput = (props: LabelBasicInputProps) => {
```
any 보다는 엄격한 type 선언은 어떨까요?

2023-04-14 08:07 UTC, 1yoouoo commented on src/components/LabelBasicSelect/index.tsx
> +const LabelBasicSelect = (props: any) => {
```suggestion
const LabelBasicSelect = (props: LabelBasicSelectProps) => {
```

2023-04-14 08:07 UTC, 1yoouoo commented on src/components/ProfileForm/index.tsx
> +  ];
```suggestion
  const mbtis: Mbti[] = [
    { id: '1', name: '선택하세요' },
    { id: '2', name: 'INFJ' },
  ];
```

2023-04-14 08:07 UTC, 1yoouoo commented on src/components/ProfileForm/index.tsx
> +  ];
배열에서 이미 복수형이 암시되어있어서 단수형[] 이렇게 작성하시면 좋을 거 같아요

2023-04-14 08:07 UTC, 1yoouoo commented on src/components/ProfileForm/index.tsx
> +  ];
이 부분은 제대로 되어있네요

2023-04-14 08:07 UTC, 1yoouoo commented on src/components/ProfileForm/index.tsx
> +      <Button text='변경완료' color='#FFFFFF' />
색상 주실 때 변수로 활용하시면 나중에 다크모드 만드실 때 편하실 거 같아요

2023-04-14 08:10 UTC, 1yoouoo commented
1. LabelBasicInput, LabelBasicSelect는 로그인, 회원가입, 프로필 페이지에서 사용하는 공통 양식이므로 스타일 양식까지 모두 통일했으면 합니다.
- @dongjoonyang 님이랑 협의 하셔서 결정하시면 될 거 같습니다.
2. LabelBasicSelect의 options값이 너무 커(Mbti의 경우 16개) 배열로 늘어놓으면 코드의 가독성이 떨어지는 단점이 있습니다.
- 이 부분은 확인을 안해봐서 모르겠습니다. 다른 방법이 있으신가요?
3. 현재 API중 GET의 users/{userID}를 페이지에 맞게 불러오는 로직에 대해 고민하고 있습니다. 페이지 내에 적용하는 것이 아닌 라우팅에 활용하는 것이라 어떻게 활용할지 감이 안잡힙니다.
- useParam 의 키워드로 구글링 해보시길 추천드립니다. react 훅입니다.
4. API를 수신하는것은 오늘 내로 가능할 것으로 예상합니다. 하지만 데이터를 서버로 송신하는것도 위의 언급처럼 현재 공부가 필요합니다.
- 모르는거 있으시면 슬랙부탁 드립니다.
5. 프로필 페이지의 취소버튼은 메인으로(취소 -> 메인으로) 변경하고 취소하기 전 alert창을 띄워 확인단계를 거치는것이 어떨까요?
- 확인창은 좋은 방법인 거 같습니다.
6. 변경완료 역시 alert창을 띄워 환인단계를 한번 거치는것이 필요하다고 생각합니다.
- 확인창은 좋은 방법인 거 같습니다.

2023-04-14 08:22 UTC, Eriniss commented
많은 부분을 동준님과 같이 작업하다보니 여러가지 부족한 면들이 보입니다. 동준님과 협의해서 빠르게 아래 피드백 수용하도록 할께요.

2023-04-14 08:23 UTC, Eriniss commented on src/components/styled-components/BasicInput.tsx
> +  Omit<InputProps, 'name' | 'id' | 'type' | 'value' | 'onChange' | 'onBlur' | 'placeholder'>
동준님과 논의하여 빠르게 반영하겠습니다.

2023-04-14 08:23 UTC, Eriniss commented on src/components/LabelBasicInput/index.tsx
> +const LabelBasicInput = (props: any) => {
이것역시 동준님과 협의하여 반영하도록 하겠습니다.

2023-04-14 08:29 UTC, Eriniss commented on src/components/ProfileForm/index.tsx
> +  ];
아 저부분 바로 반영하겠습니다

2023-04-14 08:30 UTC, Eriniss commented on src/components/ProfileForm/index.tsx
> +      <Button text='변경완료' color='#FFFFFF' />
오늘 지윤님이랑 api 커스터마이징 할때 같이 반영하겠습니다

2023-04-15 07:28 UTC, danakim530 approved these changes

2023-04-15 10:21 UTC, closed without merging